### PR TITLE
Touchpad Config File

### PR DESCRIPTION
**Pull request by robsonsilv4**
For Touchpad Support

### CODE REVIEW

**Comment by Dobbie03** [comment]
@erikdubois

**Comment by Dobbie03** [comment]
@erikdubois any ideas on this one?

**Comment by erikdubois** [comment]
not really - I have a spare laptop I can test it on... will make it my priority at a later date

**Comment by erikdubois** [comment]
in the meantime i found this code to add to my iso
still needs to be installed on a laptop
Section "InputClass"
Identifier "Touchpad" # required
MatchIsTouchpad "yes" # required
Driver "synaptics" # required
Option "MinSpeed" "0.5"
Option "MaxSpeed" "1.0"
Option "AccelFactor" "0.075"
Option "TapButton1" "1"
Option "TapButton2" "2" # multitouch
Option "TapButton3" "3" # multitouch
Option "VertTwoFingerScroll" "1" # multitouch
Option "HorizTwoFingerScroll" "1" # multitouch
Option "VertEdgeScroll" "1"
Option "CoastingSpeed" "8"
Option "CornerCoasting" "1"
Option "CircularScrolling" "1"
Option "CircScrollTrigger" "7"
Option "EdgeMotionUseAlways" "1"
Option "LBCornerButton" "8" # browser "back" btn
Option "RBCornerButton" "9" # browser "forward" btn
EndSection

**Comment by erikdubois** [comment]
is included now in 4.0.14

**Comment by erikdubois** [comment]
Let me know if you have the time to test it
then i will share a download link for the latest iso

**Pull request merged**
